openapi: 3.0.0
info:
  title: geocode
  description: A simple API allowing consumers to query for addresses and GPS coordinates.
  version: "1.0"
servers:
- url: https://localhost:8080/
paths:
  /geocode:
    get:
      summary: Single Query (GET)
      description: Resolves geocoding information for single query.  With potential
        of HTTP caching through (If-Modified-Since or eTag)
      parameters:
      - name: queryId
        in: query
        required: true
        schema:
          type: string
        example: f7bed7c3-93d8-4b61-8531-04caaad43d11
      - name: addressLine
        in: query
        schema:
          type: string
        example: Křižíkova 5, Praha 8
      - name: latitude
        in: query
        schema:
          type: number
          format: double
        example: 50.04857267339925
      - name: longitude
        in: query
        schema:
          type: number
          format: double
        example: 14.4161306290667
      - name: street
        in: query
        schema:
          type: string
        example: Podolská
      - name: streetNumber
        in: query
        schema:
          type: string
        example: "50"
      - name: districtNumber
        in: query
        schema:
          type: string
        example: "401"
      - name: town
        in: query
        schema:
          type: string
        example: Praha 4
      - name: zip
        in: query
        schema:
          type: string
        example: 147 00
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
    post:
      summary: Single Query (POST)
      description: Resolves geocoding information for single query.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SingleQuery'
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleQueryMoreResults'
      x-codegen-request-body-name: body
  /geocode/batch:
    post:
      summary: Batch Query (POST)
      description: Resolves geocoding information for multiple queries.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchQuery'
        required: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchQueryResponse'
      x-codegen-request-body-name: body
components:
  schemas:
    BatchQuery:
      title: multiple queries in a single batch
      type: array
      example:
      - queryId: f7bed7c3-93d8-4b61-8531-04caaad43d11
        addressLine: Podolská 50
        country: cz
        latitude: 50.04857267339925
        longitude: 14.4161306290667
        street: Podolská
        streetNumber: "50"
        districtNumber: "401"
        town: Praha 4
        zip: 147 00
      - queryId: 2c34e901-3601-44bf-b95f-2a232a44e1b4
        addressLine: Křižíkova 5, Praha 8
      items:
        $ref: '#/components/schemas/SingleQuery'
    BatchQueryResponse:
      title: Batch Query Response
      type: array
      example:
      - queryId: f7bed7c3-93d8-4b61-8531-04caaad43d11
        locationId: 55c9605b-2279-40cf-8271-5b01dc43af0f
        country: cz
        latitude: 50.04857267339925
        longitude: 14.4161306290667
        street: Podolská
        streetNumber: "50"
        districtNumber: "401"
        town: Praha 4
        district: Praha 4 - Podolí
        zip: 147 00
        confidence: 0.98
        services:
        - google
      - queryId: 2c34e901-3601-44bf-b95f-2a232a44e1b4
        locationId: dc109c26-7767-4476-9cbb-70f7469bc6f6
        country: cz
        latitude: 50.090285890631414
        longitude: 14.44010329319678
        street: Křižíkova
        streetNumber: "5"
        districtNumber: "254"
        town: Praha 8
        district: Praha 8 - Karlín
        zip: 186 00
        confidence: 0.98
        services:
        - google
      items:
        $ref: '#/components/schemas/QueryResponse'
    SingleQueryMoreResults:
      title: Single Query Response
      type: array
      example:
      - queryId: f7bed7c3-93d8-4b61-8531-04caaad43d11
        locationId: 55c9605b-2279-40cf-8271-5b01dc43af0f
        country: cz
        latitude: 50.04857267339925
        longitude: 14.4161306290667
        street: Podolská
        streetNumber: "50"
        districtNumber: "401"
        town: Praha 4
        district: Praha 4 - Podolí
        zip: 147 00
        confidence: 0.98
        services:
        - google
      - queryId: 2c34e901-3601-44bf-b95f-2a232a44e1b4
        locationId: dc109c26-7767-4476-9cbb-70f7469bc6f6
        country: cz
        latitude: 50.04857267339925
        longitude: 14.4161306290667
        street: Podolská
        districtNumber: "50"
        town: Mšené-lázně
        zip: 411 19
        confidence: 0.1
        services:
        - mapy.cz
      items:
        $ref: '#/components/schemas/QueryResponse'
    SingleQuery:
      title: single geocoding query
      type: object
      properties:
        queryId:
          type: string
          description: user generated ID allowing to match results in batch query
          format: uuid
          example: f7bed7c3-93d8-4b61-8531-04caaad43d11
        addressLine:
          type: string
          description: address in no particular format used in fulltext search by
            the geocoding service
          example: Podolská 50
        country:
          type: string
          format: ISO 3166-1 alpha-2
          example: cz
        latitude:
          type: number
          format: double
          example: 50.04857267339925
        longitude:
          type: number
          format: double
          example: 14.4161306290667
        street:
          type: string
          example: Podolská
        streetNumber:
          type: string
          example: "50"
        districtNumber:
          type: string
          example: "401"
        town:
          type: string
          example: Praha 4
        zip:
          type: string
          example: 147 00
        services:
          type: array
          description: keys services that will be used to fetch data
          example:
          - mapy.cz
          - google
          items:
            type: string
    QueryResponse:
      title: Query Response
      type: object
      properties:
        locationId:
          type: string
          description: ID generated when the location is first stored, if  location
            found locally, existing ID returned
          format: uuid
          example: 55c9605b-2279-40cf-8271-5b01dc43af0f
        queryId:
          type: string
          description: ID allowing to match the location to an input query, in case
            multiple queries issued
          format: uuid
          example: f7bed7c3-93d8-4b61-8531-04caaad43d11
        country:
          type: string
          format: ISO 3166-1 alpha-2
          example: cz
        latitude:
          type: number
          format: double
          example: 50.04857267339925
        longitude:
          type: number
          format: double
          example: 14.4161306290667
        street:
          type: string
          example: Podolská
        streetNumber:
          type: string
          example: "50"
        districtNumber:
          type: string
          example: "401"
        town:
          type: string
          example: Praha 4
        zip:
          type: string
          example: 147 00
        services:
          type: array
          description: service used to fetch the data, in case of merged result,  all
            services used are listed
          example:
          - mapy.cz
          - google
          items:
            type: string
        confidence:
          nullable: true
          type: number
          maximum: 1
          minimum: 0
          description: confidence index of the geocoding service - between 0 and 1,
            the higher the better
          format: double
          example: 0.8